import "./globals.css";
import {OGlobalHeader} from "~/components/organisms/OGlobalHeader";
import {cn} from "~/lib/utils";
import {inter, sansRegular} from "~/lib/fonts";
import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", inter.variable, sansRegular.variable)}>
        <OGlobalHeader />
        {children}
      </body>
    </html>
  );
}
